### ISSUE TITLE
in Bower.json it is setting the bath to src instead of dist

### ISSUE THREAD

**Issue by bdairy** [vinaygopinath/ngMeta#13]
Hi there..

the library was working fine till I think you made an update that causes two issues. the first one,, I couldn't get the file to be added to my index.html.. and when I checked . the folders are under dist,, while in bower.json is says the the main file is under "main": "src/ngMeta.js",... when  I changed the src to dist it worked.

Second thing is that you are now reserving the title and title suffex to the function setTitle. why? that caused my whole website not setting titles since I am using setTag('title','..');... I hope that you can do a quick fix for it. thanks

**Comment by vinaygopinath** [comment]
Sorry about that. It looks like I excluded the src directory from the Bower release but didn't change the main path to dist. This is now fixed in [v0.3.9](https://github.com/vinaygopinath/ngMeta/releases/tag/v0.3.9)

setTitle checks whether the titleSuffix must be appended to the title, and this is not possible with setTag. As seen in the [dynamic meta tags](https://github.com/vinaygopinath/ngMeta#dynamic-meta-tags) examples, reserving the title and titleSuffix tags for use with the setTitle function enables overriding a default titleSuffix with a custom titleSuffix at runtime, and other useful behaviour. Please replace the setTag function with setTitle for title and titleSuffix, or (not recommended) use v0.3.3.
