### ISSUE TITLE
Support changing defaults

### ISSUE THREAD

**Issue by xon88** [vinaygopinath/ngMeta#15]
Hi, thanks for the great service!

Would it be possible to add support for changing defaults? Basically, I am getting my default values from an API call, therefore it would be too late for me to set the defaults after the config is already run.

Thanks!

**Comment by vinaygopinath** [comment]
Hi,

I'm surprised to hear that you're getting your default values from an API call instead of setting some static values in the config phase and updating meta tags dynamically in routes/states using `setTitle` and `setTag`. This did not occur to me as a likely scenario while building ngMeta :)

Would you mind making a PR for `setDefaultTag` based on the [`setTag`](https://github.com/vinaygopinath/ngMeta/blob/master/src/ngMeta.js#L82-L91) code? As I see it, this new function would :
-  need to check if ngMeta was initialized and throw an error when it's not, just like `setTag`
-  not need to check if the key is title or titleSuffix.
- assign the tag to `defaults`, eg. `defaults[tag] = value;`
- check if the ngMeta[tag] is defined (i.e, Does the current state/route already define a meta tag with the same key?) If not, set `ngMeta[tag] = value`.
- need to be tested :)

I'll take a look later in the day and release a new version.

**Comment by xon88** [comment]
Hi again,

I know it's strange, but my situation is that I need to let the user change the default tags from a separate CMS, which feeds the same API the front-end consumes.

I've created the PR as requested, however I'm not sure how to attach it to this issue as it's my first one (I have however referenced the issue in the PR). I'm not sure if I've overthought things when changing the current values in the new function - I was thinking of situations where the defaults might be reset after the state/route is changed.

Please note I've also added a feature to accomodate an option for using the suffix only when the default title is overriden by the current state/route. (In my case, I am setting a default title which is identical to the default suffix, so by using this option I avoid duplication of title and suffix, and only set the suffix for the pages which override the title.)

Let me know if you have any questions =)

Regards.

**Comment by vinaygopinath** [comment]
Added in [v0.3.10](https://github.com/vinaygopinath/ngMeta/releases/tag/v0.3.10). Thanks for your help
