### ISSUE TITLE
ionic: title and meta tags are not updated

### ISSUE THREAD

**Issue by yacaeh** [vinaygopinath/ngMeta#21]
Hi, Thank you for the great Module! I'm trying to setTitle and metatags on my controller and ui-router.
I could see variable passed by using console but it doesn't update and show title as changed one. When I inspect the title, it says it's missing. (BTW I'm using Ioinc Framework and ng-inspector doesn't work properly so I'm using this chrome extention=> https://chrome.google.com/webstore/detail/seo-meta-in-1-click/bjogjfinolnhfhkbipphpdlldadpnmhc)

Title   : Title is missing!
Description : {{ngMeta.description}}

Here is my code.
index.html

```
<title ng-bind="ngMeta.title"></title>
<!-- OR <title>{{ngMeta.title}}</title> -->    

<!-- Arbitrary tags -->
<meta property="og:type" content="{{ngMeta['og:type']}}" />
<meta property="og:locale" content="{{ngMeta['og:locale']}}" />
<meta name="author" content="{{ngMeta['author']}}" />
<!-- OR <meta name="author" content="{{ngMeta.author}}" /> -->
<meta name="description" content="{{ngMeta.description}}" />

```

app.js

```
        $stateProvider
.state('app.myPage', {
            url: "/myPosts",
            views: {
                'myPost': {
                    templateUrl: "templates/themes/news-feed/html/post-my.html",
                    controller: "myPostListCtrl"
                }
            },
    data: {
      'meta': {
        'title': 'My Post- All You Need To Know | PawSquad',
        'og:title': 'All You Need To Know About Pet Vaccinations',
        'og:image': 'http://www.yourdomain.com/img/facebookimage.jpg',
        'author': 'PawSquad'
      }
    }

```

ngMeta.js

```
        var setTitle = function(title, titleSuffix) {
          console.log("Settitle called: "+title,titleSuffix);
          if (!$rootScope.ngMeta) {
            throw new Error('Cannot call setTitle when ngMeta is undefined. Did you forget to call ngMeta.init() in the run block? \nRefer: https://github.com/vinaygopinath/ngMeta#getting-started');
          }

          $rootScope.ngMeta.title = angular.isDefined(title) ? title : (defaults.title || '');
          if (config.useTitleSuffix) {
            $rootScope.ngMeta.title += angular.isDefined(titleSuffix) ? titleSuffix : (defaults.titleSuffix || '');
          }
          console.log("$rootScope.ngMeta.title"+$rootScope.ngMeta.title);
          return this;
        };

```

on console It shows everything Fine 

myAnotherController.js

```
  ngMeta.setTitle('Eluvium'); //Title = Eluvium | Playlist
  ngMeta.setTag('author', 'Matthew Cooper');
  ngMeta.setTag('image', 'http://placeholder.com/abc.jpg');
  ngMeta.setDefaultTag('author', 'Default author');

  console.log("$rootScope.ngMeta"+JSON.stringify($rootScope.ngMeta));

```

$rootScope.ngMeta{"title":"Eluvium | YourSite","og:image":"http://www.yourdomain.com/img/facebookimage.jpg","author":"Matthew Cooper","image":"http://placeholder.com/abc.jpg"}

**Comment by vinaygopinath** [comment]
Hi there,

Thanks for using ngMeta :) I'm not sure what's going on specifically with your app, but there was a mismatch between the information in the README and the version published on npm/bower, so you might be facing issues because of that. Would you mind updating to v1.0.0 and letting me know if ngMeta still fails to update the tags?

Also, you should be able to inspect the tags set on a page without any extensions using the "Inspect element" tool
![ngmeta inspect element](https://cloud.githubusercontent.com/assets/324200/19407234/e6988058-929b-11e6-838a-b3255b5e82a7.png)

**Comment by yacaeh** [comment]
Thanks for the reply :) I've updated to v1.0.0 that you uploaded and it still having the same issue. I noticed that when setTitle return this; it says this is undefined. I think that might be related to the problem. Or is it Angular version Issue? I'm using v.1.5.8 now

**Comment by vinaygopinath** [comment]
Hey @yacaeh, I don't think it's an Angular issue (everything from 1.2 onwards is supported). It looks like an implementation issue to me. As for `setTitle` returning undefined, that shouldn't be happening. All methods of ngMeta return a reference to ngMeta itself, so that you can chain multiple methods, like

``` javascript
ngMeta.setTitle('Hello', ' - Site name')
      .setTag('og:image', 'http://example.com/img.png');
```

A few questions:
1. How have you included ngMeta? Are you using a package manager like npm or bower?
2. Is your code public?

I haven't checked how well/if ngMeta works with ionic. Has anyone else successfully used ngMeta in combination with ionic?

**Comment by yacaeh** [comment]
Hi @vinaygopinath To answer your questions
1. I've included via dist file, and tried CDN.
2. Okay, I cause my project is not public I will try to make codepen for it

And I heard some of ionic users failed to use this. I don't know why this is happening but seems it's ionic issue

**Comment by JensWinter** [comment]
Hi @yacaeh,

make sure you have registered your app on the html element:

```
<html ng-app="MyApp">
   <head>
...
   </head>
```

I had the same symptoms as you. This is what solved my problems.

Cheers,
Jens

**Comment by stasinua** [comment]
I have the same issue. The 'content' field just remains empty. And I`ve registered my application on <html> tag. I don`t using Ionic, but Angular 1.5.8. I will post here workaround if I find it.
