### ISSUE TITLE
Doesn't work for skype links preview

### ISSUE THREAD

**Issue by pitometsyurii** [vinaygopinath/ngMeta#23]
http://vinaygopinath.github.io/ngMeta/#/

Send this link someone on skype and it will not show correct page preview.

**Comment by stasinua** [comment]
Because simple previewers(crawlers) don`t execute Javascript. It`s not a library problem.
You can read following articles if you want to enable rich social sharing for Angular SPA:
1. For Node.js server: [https://code.tutsplus.com/tutorials/adding-social-sharing-in-a-nodejs-single-page-application--cms-25530](https://code.tutsplus.com/tutorials/adding-social-sharing-in-a-nodejs-single-page-application--cms-25530)
2. For PHP server: [http://www.michaelbromley.co.uk/blog/171/enable-rich-social-sharing-in-your-angularjs-app](http://www.michaelbromley.co.uk/blog/171/enable-rich-social-sharing-in-your-angularjs-app)

**Comment by vinaygopinath** [comment]
Hi @yupitomets,

As @stasinua said, it's not an issue with ngMeta. Skype's crawler probably doesn't execute Javascript, so it sees the raw `{{ngMeta.title}}` as the title, instead of the value set by `ngMeta`.

Please read the [Support for other crawlers](https://github.com/vinaygopinath/ngMeta#support-for-other-crawlers) section of the README. I also just wrote a post explaining it in further detail on [my blog](http://vinaygopinath.me/blog/tech/social-media-rich-snippets-with-angularjs-and-ngmeta/).

If you don't want to use pre-rendering or a server-side redirect, the last section in my blog post might be of use. Try something like 
```html
<meta property="og:title" content="Site name" ng-if="false" />
<meta property="og:description" content="Site description" ng-if="false" />
```
Any non-Javascript crawler (AFAIK, that's most crawlers. Only Google search's crawler executes Javascript) would pick up `Site name` and `Site description` as the title and description values.
