### ISSUE TITLE
Google indexing issue with ngMeta

### ISSUE THREAD

**Issue by BobKlaas** [vinaygopinath/ngMeta#3]
I'm using ngMeta and when I inspect the my head tag using the Chrome console, I see ngMeta is in fact changing my meta values. So, at first glance, I thought this solution was working. However, Google is not indexing those values. Instead it is indexing the description {{ngMeta.description}} when it crawls my page. Any idea how to fix this?

Website: www.klaasrealty.net | Google Search: klaas realty

![untitled](https://cloud.githubusercontent.com/assets/5191616/12765117/dd63c136-c9b1-11e5-9902-bbaeaf80efce.png)

**Comment by vinaygopinath** [comment]
I had a quick look at your site's source, and it looks like you have this in your root HTML file

``` html
<title ng-bind="{{ngMeta.title}}"></title>
```

Please replace that with either

``` html
<title ng-bind="ngMeta.title"></title>
```

or

``` html
<title>{{ngMeta.title}}</title>
```

**Comment by vinaygopinath** [comment]
Are you sure you're not running into errors while running your site locally? ngMeta doesn't seem to be running. For a quick look at the ngMeta tags set for a route, check out the ngMeta object in the $rootScope of the app using [ng-inspector](https://chrome.google.com/webstore/detail/ng-inspector-for-angularj/aadgmnobpdmgmigaicncghmmoeflnamj), or add this to the HTML template of the route.

``` html
<pre>
{{ngMeta | json }}
</pre>
```

A few other issues: 

In [`listingdetail.js`](http://www.klaasrealty.net/app/listings/listingdetail.js), you're using `ngMeta.setTag('title', '....')`. Please use `ngMeta.setTitle` instead. This is because title is treated as a special tag (fallback to default title + appending the given/default suffix when `ngMetaProvider.useTitleSuffix(true)`)

Unrelated:
In the same file, I see

```
ngMeta.setTag("url", "http://www.klaasrealty.net/#!/view" + $scope.listing.listinguid)
```

Tip: Hashbang (#!) URLs are [no longer recommended](https://googlewebmastercentral.blogspot.rs/2015/10/deprecating-our-ajax-crawling-scheme.html). Consider enabling [html5Mode](https://docs.angularjs.org/guide/$location).

**Comment by BobKlaas** [comment]
@vinaygopinath I added the <pre> tag as you suggested. When I change routes, I see the ngMeta object updating as intended for every route. I also changed the function for title to setTitle() as you suggested. At face value, everything seems to be working correctly. However, Google is reading {{ngMeta.description}} as text when it gets crawled. Any additional suggestions?

Also, I must have forgot to update that meta url path. Thanks for pointing that out.

**Comment by BobKlaas** [comment]
@vinaygopinath I fixed the title bind attribute and I added the pre tag as you suggested. When I change routes, I see the ngMeta object updating as intended for every route. I also changed the function for title to setTitle() as you suggested. At face value, everything seems to be working correctly. However, Google is reading {{ngMeta.description}} as text when it gets crawled. Any additional suggestions?

Also, I must have forgot to update that meta url path. Thanks for pointing that out.

**Comment by vinaygopinath** [comment]
I can't seem to figure out what's wrong from the site. Would you mind letting me access your code base?

**Comment by BobKlaas** [comment]
@vinaygopinath  sure thing. I added you as a collaborator.  (https://github.com/BobKlaas/klaasrealty2)

**Comment by vinaygopinath** [comment]
I'll take a look, thanks. Meanwhile, if you haven't already set up Google webmaster tools, can you do that and recrawl your site using Crawl --> Fetch as Google + submit it to index?

**Comment by BobKlaas** [comment]
Right on. Thanks for your help. I've been doing the Fetch as Google pretty much every day for the last few weeks. But, it still appears to be grabbing {{ngMeta}} instead of the underlying value. I've been troubleshooting this for 2 weeks and I've yet to figure to find a solution. :(

**Comment by vinaygopinath** [comment]
The [changefreq](http://www.sitemaps.org/protocol.html) in your [sitemap.xml](https://github.com/BobKlaas/klaasrealty2/blob/master/sitemap.xml) is set to `monthly`. This is probably affecting the SERP snippet generated for your site. Consider temporarily changing it to `always` or removing the sitemap.xml.

ngMeta seems to be working properly on the site. You might want to dig into your IIS config to make sure crawlers have access to JS files and are not being redirected.

**Comment by vinaygopinath** [comment]
@BobKlaas Looks like changing the sitemap.xml fixed it. 
![screencapture-www-google-rs-search-1455576234305](https://cloud.githubusercontent.com/assets/324200/13062428/e39fbacc-d43e-11e5-9a1f-8f13eba67ff7.png)

P.S: The contact.html snippet looks like the remnant of a previous iteration of the site. You should be able to remove it from webmaster tools and/or robots.txt.

**Comment by heshamelmasry77** [comment]
same shit it is not working
